# Generated by Django 4.2.2 on 2023-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='img/default.png', upload_to='profile_pictures/'),
        ),
    ]
