# Generated by Django 4.2.2 on 2023-06-09 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_announcement'),
        ('accounts', '0005_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='img/default.png', upload_to='profile_pictures/')),
                ('church_member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='members.churchmember')),
            ],
        ),
    ]
