# Generated by Django 4.2.2 on 2023-06-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='service_group_meetings_attended', to='members.churchmember')),
                ('service_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='members.servicegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='church_attendance', to='members.churchmember')),
            ],
        ),
        migrations.CreateModel(
            name='CellGroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('attendees', models.ManyToManyField(related_name='cell_group_meetings_attended', to='members.churchmember')),
                ('cell_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='members.cellgroup')),
            ],
        ),
    ]
