# Generated by Django 4.2.2 on 2023-06-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_servicegroupmeeting_churchattendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellgroup',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cellgroup',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cellgroup',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cellgroup',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
