# Generated by Django 4.2.2 on 2023-06-06 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_cellgroup_name_alter_servicegroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchattendance',
            name='children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='churchattendance',
            name='men',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='churchattendance',
            name='women',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='churchattendance',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='church_attendance', to='members.churchmember'),
        ),
    ]
