# Generated by Django 4.2.2 on 2023-06-06 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_churchattendance_other_service_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchattendance',
            name='attendees',
        ),
        migrations.CreateModel(
            name='ChurchAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('service_type', models.CharField(choices=[('MID_WK', 'Wednesday Midweek'), ('SUN', 'Sunday'), ('WOSE', 'Week of Spiritual Emphasis'), ('SHILOH', 'Shiloh'), ('ANNI', 'Anniversary'), ('LE_SUB', 'Leadership Empowerment Summit'), ('OTHER', 'Others')], default='SUN', max_length=20)),
                ('other_service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('church_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='members.churchattendance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.churchmember')),
            ],
        ),
    ]
