# Generated by Django 4.2.2 on 2023-06-06 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_churchattendance_attendees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovenantHourOfPrayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('venue', models.CharField(choices=[('zoom', 'Zoom'), ('church_premise', 'Church Premise'), ('others', 'Others')], default='zoom', max_length=20)),
                ('other_venue', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
