# Generated by Django 4.2.2 on 2023-06-06 21:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_covenanthourofprayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchmember',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_active_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_baptized',
            field=models.BooleanField(default=False, help_text='Baptised by immersion in water'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_confirmed_member',
            field=models.BooleanField(default=False, help_text='Established member of the church'),
        ),
        migrations.AlterField(
            model_name='churchmember',
            name='is_new_member',
            field=models.BooleanField(default=False, help_text='New member of the church'),
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('New Member', 'New Member'), ('Inactive Member', 'Inactive Member'), ('Thank You', 'Thank You')], max_length=20)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('recipients', models.ManyToManyField(related_name='newsletters', to='members.churchmember')),
            ],
        ),
    ]
