# Generated by Django 4.2.2 on 2023-06-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_carouselimage_testimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='announcement_images/')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
