# Generated by Django 4.2.2 on 2023-06-11 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tithly_offering', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tithe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shiloh', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thanksgiving', models.DecimalField(decimal_places=2, max_digits=10)),
                ('welfare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='members.finance')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.finance')),
            ],
        ),
    ]
