# Generated by Django 4.2.2 on 2023-06-11 09:13

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_tithlyoffering_remove_finance_tithly_offering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='finance',
            name='purpose',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 9, 13, 40, 703593, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finance',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='offering',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='project',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='shiloh',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='thanksgiving',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='tithe',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='finance',
            name='welfare',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
