# Generated by Django 4.2.2 on 2023-06-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_remove_expense_finance_remove_finance_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finance',
            name='net_balance',
        ),
    ]
